repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dense-analysis/ale
    rev: v0.2.1
    hooks:
      - id: rustfmt
      - id: rust-clippy
        args: ["--", "-D", "warnings"]

  - repo: https://github.com/cocogitto/cocogitto
    rev: "3.2"
    hooks:
      - id: conventional-commit
        args: ["--keyword", "feat,fix,refactor,docs,chore,test"]
